version: 0.0
os: linux
files:
  - source: docker-compose-files.tar.gz
    destination: /home/ec2-user
  - source: appspec.yml
    destination: /home/ec2-user
file_exists_behavior: OVERWRITE
hooks: 
  AfterInstall:
    - location: install_deps.sh
      runas: ec2-user
      working_directory: /home/ec2-user
  ApplicationStart:
    - location: deploy.sh
      runas: ec2-user
      working_directory: /home/ec2-user