version: 0.2

phases:
  pre_build:
    commands:
      - echo setting up env script...
      - cd ec2
      - |
        cat <<EOF | ./envsetup.sh
        y
        $AMBAR_HOST_ADDRESS
        $AMBAR_API_ADDRESS
        EOF
      - cd ..
  build:
    commands:
      - echo building docker images
      - ./push2ecr.sh
  artifacts:
    files:
      - 'docker-compose.yml'
      - '.env'
    name: docker-compose-files
    discard-paths: no