version: 0.2

phases:
  pre_build:
    commands:
      - echo setting up env script...
      - |
        cat <<EOF | ./envsetup.sh
        y
        $AMBAR_HOST_ADDRESS
        $AMBAR_API_ADDRESS
        EOF
      - cat .env