version: 0.2

phases:
  pre_build:
    commands:
      - echo setting up env script...
      - cd ec2
      - |
        cat <<EOF | ./envsetup.sh
        y
        $AMBAR_HOST_ADDRESS
        $AMBAR_API_ADDRESS
        EOF
      - cd ..
  build:
    commands:
      - echo building docker images
      - ./push2ecr.sh
  post_build:
    commands:
      - echo zipping artifacts
      - tar -czf docker-compose-files.tar.gz docker-compose.yml .env
artifacts:
  files:
    - 'docker-compose-files.tar.gz'
  name: docker-compose-files
  discard-paths: no